version: "3.8"

services:
  php:
    build: .
    container_name: php_ecommerce_php
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=ecommerce_db
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=supersecret
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ecommerce_net

  nginx:
    image: nginx:1.25
    container_name: php_ecommerce_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - ecommerce_net

  db:
    image: mysql:8.0
    container_name: php_ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - ecommerce_net
volumes:
  db_data:

networks:
  ecommerce_net:
    driver: bridge